# Custom Language File for Launcher Customizer

[ejs.app]
title = "I&A"

[ejs.landing]
mediaGitHubURL = "https://github.com/DEVxKIS/Kenetic-Castes"
mediaBoostyURL = "https://boosty.to/iamods"
mediaTwitterURL = "#"
mediaVKURL = "#"
mediaRuTubeURL = "https://rutube.ru/channel/38559212/"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://www.youtube.com/@IAMods"
mediaDiscordURL = "https://discord.gg/amNcjeKhyT"

[ejs.settings]
sourceGithubLink = "https://github.com/DEVxKIS/Kenetic-Castes"
supportLink = "https://github.com/DEVxKIS/Kenetic-Castes/issues"

[ejs.welcome]
welcomeHeader = "Привет"
welcomeDescription = "."
welcomeDescCTA = "..."
